### ISSUE TITLE
Optimize home page title and  header for SEO

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eoscostarica.io#411]
We should replace the word solutions for development as it is a better keyword
![image](https://user-images.githubusercontent.com/5632966/124396884-83a38100-dcc9-11eb-8be4-c01aa44a22d5.png)

`<h1>Enterprise Blockchain <br> Development That <br> Fit Your Needs</h1>`

![image](https://user-images.githubusercontent.com/5632966/124396130-1261cf00-dcc5-11eb-84dc-4b2144a8aea5.png)

@AngeloCG97 pls change both the header and metatitle to: 
**EN**
- Header: "Enterprise Blockchain Development to Fit Your Needs"
- Metatitle: "Enterprise Blockchain Development"

**ES**
- Header: "Desarrollo blockchain a la medida para su empresa"
- Metatitle: "Desarrollo blockchain empresarial"

**Comment by xavier506** [comment]
en español: 

Desarrollo blockchain a la medida para su empresa ?

**Comment by ldrojas** [comment]
@xavier506 I agree with 'development' being a better keyword, but 'solutions' is broader since we offer not only development services but also infrastructure and learning/training. I'll change it and see how it works out.

**Comment by xavier506** [comment]
@ldrojas  perhaps we can set development in the keyword for the page title yet keep the header as solutions?
