### ISSUE TITLE
Template Engine / Static Site Generator 

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eoscostarica.io#8]
We need to use templates in order to avoid duplication of code and make the site easier to maintain. Let's discuss here what static site generator we want to use.

Here's the full list
https://www.staticgen.com

I have used hexo, harpjs and hugo.  Hexo is nice for blogs, Harp uses Jade ( which is not that common ) and I felt it kinda clunky.  Of all 3 I prefer Hugo, though it doesn't have website optimization out of the box so I published this project which does [gaboesquivel/fasthugo](https://github.com/gaboesquivel/fasthugo) ( 🏂 FastHugo is an Optimized Hugo Static Website Boilerplate ), however it still needs more love to get it to the point that I want. 

There are other interesting ones like

- https://www.staticgen.com/vuepress 
- https://www.staticgen.com/gatsby

Let's take the time to analyze options and decide. Please leave your comments and recommendations

**Comment by xavier506** [comment]
@gaboesquivel  

Wow so many options... I think Hugo seems like a good starting point.  It is widely used and documented and it seems we already have some projects using it.

**Comment by gaboesquivel** [comment]
Agree, let's try hugo.io. It has good support for i18n too. 
btw nice find the new hugo assets pipeline, that removes the need for fasthugo at least for concatenation and minification of css and js.  Later on we might want to implement automatic image compression and optimizations from fasthugo. Not critical, right now.

I think we should work on a branch right here on on https://github.com/eoscostarica/ so it's easier collaborate. PR to the `hugo` branch.
